#!/usr/bin/env python3
"""
03_fig3_syndicate_sensitivity.py
===================================
Figure 3 (dissertation, rebuilt): sensitivity of the first-round
syndicate-size effect (two investors vs. one) across four specifications
that ARE independently verifiable from this repository's own scripts:

  1. Primary model (categorical syndicate + year fixed effects, Equation 1)
     -- see 07_main_model.py / Table 4.
  2. Log-syndicate + year fixed effects variant
     -- see 13_full_diagnostics_and_variants.py.
  3. Post-2013 founding-cohort restriction (same categorical + year-FE form)
     -- see 13_full_diagnostics_and_variants.py.
  4. Confirmed-liquidity outcome, categorical syndicate (Equation 2)
     -- see 13_full_diagnostics_and_variants.py.

This replaces the original Figure 3, which mixed exposure-time diagnostics
that could not be independently reproduced with a log-syndicate estimate
that also could not be located anywhere in this project's files. Every
point plotted here has a coefficient CSV in code/analysis/outputs/ that can
be regenerated by re-running 07_main_model.py and
13_full_diagnostics_and_variants.py.

Input: code/analysis/outputs/{main_model_categorical_yearfe_results.csv,
       main_model_log_syndicate_yearfe_results.csv,
       main_model_post2013_yearfe_results.csv,
       confirmedexit_categorical_yearfe_results.csv}
Output: outputs/fig3_syndicate_sensitivity.png
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import ANALYSIS_OUTPUTS, outputs_dir  # noqa: E402


def get_or_ci(csv_name: str, row_label: str):
    df = pd.read_csv(ANALYSIS_OUTPUTS / csv_name, index_col=0)
    row = df.loc[row_label]
    return row["OR"], row["OR_lo"], row["OR_hi"], row["p"]


def main() -> None:
    specs = [
        ("Confirmed-liquidity outcome\n(categorical, Equation 2)",
         *get_or_ci("confirmedexit_categorical_yearfe_results.csv",
                     "C(syndicate_cat, Treatment(reference='1'))[T.2]")),
        ("Post-2013 founding cohort\n(categorical + year FE)",
         *get_or_ci("main_model_post2013_yearfe_results.csv",
                     "C(syndicate_cat, Treatment(reference='1'))[T.2]")),
        ("Log-syndicate + year FE",
         *get_or_ci("main_model_log_syndicate_yearfe_results.csv",
                     "np.log(first_round_syndicate_size)")),
        ("Primary model\n(categorical + year FE, Equation 1)",
         *get_or_ci("main_model_categorical_yearfe_results.csv",
                     "C(syndicate_cat, Treatment(reference='1'))[T.2]")),
    ]

    fig, ax = plt.subplots(figsize=(9.2, 4.2))
    y_pos = np.arange(len(specs))
    for i, (label, orv, lo, hi, p) in enumerate(specs):
        ax.plot([lo, hi], [i, i], color="#3366cc", lw=2, zorder=2)
        ax.scatter([orv], [i], color="#3366cc", s=90, zorder=3)
        sig = "*" if p < 0.05 else "n.s."
        ax.annotate(f"{orv:.2f} [{lo:.2f}, {hi:.2f}] ({sig})", xy=(hi, i),
                    xytext=(8, 0), textcoords="offset points", va="center", fontsize=9.5, color="#4a4a4a")

    ax.axvline(1.0, color="black", linestyle="--", lw=1, zorder=1)
    ax.set_yticks(y_pos)
    ax.set_yticklabels([s[0] for s in specs], fontsize=10)
    ax.set_xscale("log")
    ax.set_xticks([0.1, 0.25, 0.5, 1, 2])
    ax.get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
    ax.xaxis.set_minor_locator(matplotlib.ticker.NullLocator())
    ax.set_xlim(0.08, 2.3)
    ax.set_xlabel("Odds ratio, two investors vs. one (log scale); dashed line = no association")
    ax.set_title("Figure 3. Sensitivity of the first-round syndicate-size effect\nacross independently verifiable specifications",
                  fontsize=12.5)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout()

    out = outputs_dir() / "fig3_syndicate_sensitivity.png"
    fig.savefig(out, dpi=200)
    print(f"Wrote {out}")
    for label, orv, lo, hi, p in specs:
        print(f"  {label.splitlines()[0]}: OR={orv:.3f} [{lo:.3f}, {hi:.3f}], p={p:.4g}")


if __name__ == "__main__":
    main()
